{
  "on": {
    "branch": "master"
  },
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    ". \"stable\""
  ],
  "script": [
    "npm install",
    "npm test",
    "npm run build"
  ],
  "deploy": [
    {
      "provider": "surge",
      "skip_cleanup": true,
      "domain": "react-test-case.surge.sh",
      "project": "./build/"
    }
  ]
}